# Generated by Django 2.1.1 on 2018-09-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=255)),
                ('cod_product', models.IntegerField()),
                ('amount_product', models.IntegerField()),
                ('prince_product', models.DecimalField(decimal_places=2, max_digits=7)),
                ('img_product', models.ImageField(blank=True, null=True, upload_to='produtos_photos')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Produtos',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
